# Generated by Django 3.2.20 on 2023-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230830_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_zsapif', upload_to='images/'),
        ),
    ]
